networks:
  blab:
    driver: bridge

services:
  emqx:
    image: emqx/emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    networks:
      - blab

  sherpa:
    image: ghcr.io/meha4j/sherpa:latest
    ports:
      - "20041:8080"
    environment:
      - server.port=8080
      - server.frame.length=16384
      - platform.mqtt.host=emqx
      - platform.mqtt.port=1883
    depends_on:
      - emqx
    networks:
      - blab
